services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: peerzee
      POSTGRES_PASSWORD: peerzee
      POSTGRES_DB: peerzee-db
    ports:
      - "5456:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - peerzee-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U peerzee -d peerzee-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./peerzee-backend
      dockerfile: Dockerfile
    env_file:
      - ./peerzee-backend/.env
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - peerzee-network
    restart: unless-stopped

  frontend:
    build:
      context: ./peerzee-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:9000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:9000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - peerzee-network
    restart: unless-stopped

volumes:
  pgdata:


networks:
  peerzee-network:
    driver: bridge
